### ISSUE TITLE
支援多層級的 Overlay views

### ISSUE THREAD

**Issue by amoshsueh** [fatbobman/SwiftUIOverlayContainer#2]
SwiftUIOverlayContainer 目前看起來僅支援單一 layer 的 overlay，不知道未來能不能支援多層級的呈現方式，這樣設計畫面會更有彈性，謝謝提供這麼好的一個思路。

**Comment by fatbobman** [comment]
我确实有升级overlay container的想法。目前还没有完全成熟。多层级肯定在考虑之中。

**Comment by fatbobman** [comment]
刚更新到2.0版本。可支持多容器，多layer，以及一些其他功能。

**Comment by amoshsueh** [comment]
太有效率了，我來好好體驗一下，再跟您回報結果，感激不盡！
