### ISSUE TITLE
UUID for content view

### ISSUE THREAD

**Issue by amoshsueh** [fatbobman/SwiftUIOverlayContainer#6]
您好：

從文件上得知容器管理器目前提供的方法有：
> - show(view: Content, in container: String, using configuration: ContainerViewConfigurationProtocol, animated: Bool) -> UUID?
>    在指定的容器中显示视图，返回值为视图的 ID
> - dismiss(view id: UUID, in container: String, animated flag: Bool)
>   在指定的容器中，撤销指定 ID 的视图

假設我從 A view 呼叫 container manager 去 show B view，我會取得一個 uuid，那有什麼方法可以讓 B view 直接取得這個 uuid 讓 dismiss(view id: UUID, in container: String, animated flag: Bool) 可以順利執行呢？

 p.s. 目前想到可以用 Closure 的方式，想問問看有沒有更好的方法，謝謝！

**Comment by amoshsueh** [comment]
抱歉，我試了 closure 的方式會有 Circular reference 的問題，看來是不可行。

**Comment by fatbobman** [comment]
你好，如果在两个并非祖孙关系的视图之间传递数据，无非以下几种手段：
* 使用在公共的祖先上创建的Source of truth，例如：@State，@StateObject
* viewA中通过preferenceValueKey传递值给上层视图，祖先视图通过onPreference将值保存到source of truth中，viewB直接使用该source
* 通过FocusedValueKey在两个视图之间传递 （https://fatbobman.com/posts/focusedBinding/）

另外，如果弹出视图内容较少，也可以在公共祖先视图创建一个 isPresented 值，在ViewA中通过调用Binding的方式来展示视，图，这样ViewB只需要将isPrensented设置为false即可。

不过你的这个问题给了我另外的启发，我刚刚修改了show方法的参数：
```swift
// 从
show(view: Content, in container: String, using configuration: ContainerViewConfigurationProtocol, animated: Bool) -> UUID?
// 改为
show(view: Content, with ID: UUID?, in container: String, using configuration: ContainerViewConfigurationProtocol, animated: Bool) -> UUID?
```
这样，开发者可以自己指定ID（如果不指定，show方法会为你生成）。这样可以给开发者更多的控制能力。

**Comment by amoshsueh** [comment]
你好，感謝回覆和提供這些思路。

另外建議一點，如果能夠直接支援關閉最上層的視圖會更加方便（這應該是最常用到的功能） ，給你參考：

`dismissTopestView(in container: String, animated flag: Bool)`

**Comment by fatbobman** [comment]
谢谢你的建议，我会不久之后添加上
